language: python
python:
- '3.7'
cache: pip
before_install:
- sudo apt-get install python-dev
- sudo apt-get install -y libpq-dev
install:
- pip install pipenv
- pipenv install
- pip install coverage
before_script:
- wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TJ4QRJk_7n-Zh1u9zz6mRwlBXYHukfvl' -O x13as
- chmod +x x13as
- cp x13as /home/travis/build/rxavier/econuy/econuy/resources
- sudo apt-get install unrar
script:
- coverage run -m pytest
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: __token__
  password:
    secure: buN1Fgdx76cJOameoS9PZQCsoHpnXLFzx8amlfXh67WXyrAGy3YhD/7snK1ndGeLxQ+wz9HJh/2QsptsLRrA3yZ2gwzoIguCRIOB0ieUwAF9Bid0oMJjWRqzI0/ARtBY/6XzOVYhPRDH/xx79y6+o96Us5F3+d80/Qe8T1T78nt76MByEfbbuHEDO1tIMnc2LpeSMCAwJSXuzKhClWBW5q7FKD33kt+CdiCixK2HIGG6NQ/p34/sK87qVmbvr+bqJZ4HQhHeuyxBb0bUwyW6JvtAF3EkRTuNonbPMUkbguG4rElKcgVlLuHjkkqbvzP4kh+YjO37EAynRQjLni2Brh9Y8zImPRme8f1t3iO2ZulnsjkSjPHbQpIDujbMR2SUNfOmLVHEZ+Khacv84TUc/61dZ732/7OczfmH36jzQdHRtC6mtq3OlA+kV5IfQ8SCMcz5vCYdkeLLrHCercAAJ71Il7ugmSS8BujD/GSyr/8cxsDqM5L+L7CboMmw9RmmtYdFHs26kwqpA2TIH+erkKrlFgXrQoB84jBpfY0ehII0K2v3K/zmdy6OpW16q4wCAW/AQHl/7L/TdUu3r2eo8pr66qZ/huswGNlxcATPP5kgQs/mgsTNBrIbas4Z3y8YTLKlsApoJ2hNgOilVBquVZZ7Lx7aZtpsMT4WZOB9GLs=
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
