language: python
python:
  - "3.7"
cache: pip
install:
  - pip install pipenv
  - pipenv install
before_script:
  - wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TJ4QRJk_7n-Zh1u9zz6mRwlBXYHukfvl' -O x13as
  - chmod +x x13as
  - cp x13as /home/travis/build/rxavier/econuy/econuy/resources
  - sudo apt-get install unrar
script:
  - pipenv run coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)